### ISSUE TITLE
SetupServer.jar crashes in a headless environment if you don't have the right java version.

### ISSUE THREAD

**Issue by solarmist** [ATLauncher/Server-Setup#1]
I needed to setup X11 tunneling just so the jar could tell me I needed to update my version of java.

**Comment by RyanTheAllmighty** [comment]
This is not an issue of this program as there is nothing which checks or tells you to upgrade/change Java, this is most likely either your OS telling you that or the pack. Please submit an issue with wherever that packs support is.
